version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis-cache
    ports:
      - "6379:6379"

  server:
    build: ./server
    container_name: server-app
    ports:
      - "5000:5000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - ./server:/app
      - /app/node_modules

  client:
    build: ./client
    container_name: client-app
    ports:
      - "5173:5173"
    depends_on:
      - server
    volumes:
      - ./client:/app
      - /app/node_modules
