INSERT INTO `provinsi` (`nama_provinsi`) VALUES 
('Aceh'),
('Sumatera Utara'),
('Sumatera Barat'),
('Riau'),
('Jambi'),
('Sumatera Selatan'),
('Bengkulu'),
('Lampung'),
('Kepulauan Bangka Belitung'),
('Kepulauan Riau'),
('DKI Jakarta'),
('Jawa Barat'),
('Jawa Tengah'),
('DI Yogyakarta'),
('Jawa Timur'),
('Banten'),
('Bali'),
('Nusa Tenggara Barat'),
('Nusa Tenggara Timur'),
('Kalimantan Barat'),
('Kalimantan Tengah'),
('Kalimantan Selatan'),
('Kalimantan Timur'),
('Kalimantan Utara'),
('Sulawesi Utara'),
('Sulawesi Tengah'),
('Sulawesi Selatan'),
('Sulawesi Tenggara'),
('Gorontalo'),
('Sulawesi Barat'),
('Maluku'),
('Maluku Utara'),
('Papua Barat'),
('Papua');

INSERT INTO `upt` (`nama_upt`) VALUES 
('UPT Seismologi Jakarta'),
('UPT Seismologi Padang Panjang'),
('UPT Seismologi Yogyakarta'),
('UPT Seismologi Denpasar'),
('UPT Seismologi Manado'),
('UPT Seismologi Makassar'),
('UPT Seismologi Ambon'),
('UPT Seismologi Jayapura');

INSERT INTO `jaringan` (`nama_jaringan`) VALUES 
('Jaringan Seismologi Nasional'),
('Jaringan Akselerograf'),
('Jaringan Broadband'),
('Jaringan Real Time');