INSERT INTO `provinsi` (`nama_provinsi`) VALUES 
('Nusa Tenggara Timur'),
('Maluku'),
('Jawa Timur'),
('Bengkulu'),
('Jawa Barat'),
('Papua Barat'),
('Sulawesi Tengah'),
('Papua'),
('Aceh'),
('Sulawesi Selatan'),
('Sulawesi Tenggara'),
('Bali'),
('Maluku Utara'),
('Sumatera Barat'),
('Kalimantan Timur'),
('Riau'),
('Sumatera Selatan'),
('Jawa Tengah'),
('Jambi'),
('Nusa Tenggara Barat'),
('Banten'),
('Kalimantan Tengah'),
('Papua Selatan'),
('Yogyakarta'),
('Sumatera Utara'),
('Gorontalo'),
('Kalimantan Selatan'),
('Kalimantan Barat'),
('Lampung'),
('Sulawesi Utara'),
('Sulawesi Barat'),
('Kalimantan Utara'),
('Bangka Belitung'),
('Kepulauan Riau'),
('Jakarta');

INSERT INTO `upt` (`nama_upt`) VALUES 
('Stageof-Alor'),
('Stageof-Ambon'),
('Stageof-Pasuruan'),
('Stageof-Kepahiang'),
('Stageof-Bandung'),
('Stageof-Sorong'),
('Stageof-Palu'),
('Stageof-Jayapura'),
('Stageof-Maluku-Tenggara-Barat'),
('Stageof-Kupang'),
('Stageof-Nabire'),
('Stageof-Nganjuk'),
('Stageof-Aceh-Selatan'),
('Stageof-Sumba-Timur'),
('Stageof-Gowa'),
('Stageof-Kendari'),
('Stageof-Denpasar'),
('Stageof-Ternate'),
('Stageof-Aceh-Besar'),
('Stageof-Padang-Panjang'),
('Stageof-Balikpapan'),
('Stageof-Tangerang'),
('Stageof-Banjarnegara'),
('Stageof-Lampung-Utara'),
('Stageof-Mataram'),
('Stageof-Sukabumi'),
('Stageof-Deli-Serdang'),
('Stageof-Malang'),
('Stageof-Sleman'),
('Stageof-Gunung-Sitoli'),
('Stageof-Gorontalo'),
('Stageof-Manado'),
('DGT');

INSERT INTO `jaringan` (`nama_jaringan`) VALUES 
('MR2020'),
('LIBRA'),
('China'),
('INA Minireg'),
('INA Type-A'),
('IDRIP83'),
('INA Type-B'),
('REIS'),
('ALOPTAMA 2023'),
('CTBTO'),
('GFZ'),
('ALOPTAMA 2022'),
('BB2021'),
('REPLACEMENT 2024'),
('IDRIP Phase II'),
('JICA'),
('JISNET'),
('BABUN');