CREATE TABLE `stasiun` (
  `stasiun_id` integer PRIMARY KEY AUTO_INCREMENT,
  `net` varchar(2),
  `kode_stasiun` varchar(8) UNIQUE NOT NULL,
  `lintang` float,
  `bujur` float,
  `elevasi` float,
  `lokasi` text,
  `provinsi_id` integer,
  `upt_id` integer,
  `status` varchar(10),
  `tahun_instalasi` integer,
  `jaringan_id` integer,
  `prioritas` varchar(5),
  `keterangan` text NULL,
  `accelerometer` varchar(20),
  `digitizer_komunikasi` text,
  `tipe_shelter` varchar(10),
  `lokasi_shelter` varchar(30),
  `penjaga_shelter` varchar(10),
  `kondisi_shelter` varchar(20),
  `assets_shelter` text,
  `conditions_shelter` text,
  `access_shelter` text,
  `photo_shelter` text,
  `penggantian_terakhir_alat` datetime,
  `updated_at` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);