CREATE TABLE `latency_history` (
  `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
  `sta` VARCHAR(10) NOT NULL,
  `ipaddr` VARCHAR(45),
  `net` VARCHAR(10),
  `time_from_api` DATETIME,
  `latency1` INT,
  `latency2` INT,
  `latency3` INT,
  `latency4` INT,
  `latency5` INT,
  `latency6` INT,
  `ch1` VARCHAR(10),
  `ch2` VARCHAR(10),
  `ch3` VARCHAR(10),
  `ch4` VARCHAR(10),
  `ch5` VARCHAR(10),
  `ch6` VARCHAR(10),
  `location` VARCHAR(255),
  `provin` VARCHAR(50),
  `uptbmkg` VARCHAR(100),
  `longitude` DECIMAL(10, 6),
  `latitude` DECIMAL(10, 6),
  `recorded_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
