ALTER TABLE `stasiun` 
  MODIFY COLUMN `lintang` DECIMAL(10, 7) DEFAULT NULL,
  MODIFY COLUMN `bujur` DECIMAL(10, 7) DEFAULT NULL;



ALTER TABLE `stasiun_history` 
  MODIFY COLUMN `latitude` DECIMAL(10, 7) DEFAULT NULL,
  MODIFY COLUMN `longitude` DECIMAL(10, 7) DEFAULT NULL;
